name: StoneDrop
description: This plugin makes mining stone way more fun and addictive. What it does is it enables players to have additional loot dropped from stone, not just this boring cobblestone.
api-version: 1.13
version: 2.1.0
main: me.apisek12.StoneDrop.PluginMain
commands:
  shutdown:
    description: Op/console-only command. cancels shutdown if it has been initialized.
  cancelShutdown:
    description: Op/console-only command. cancels shutdown if it has been initialized.
  drop:
    aliases:
      - d
    description: Plugin's base command.
  whatdrops:
    description: Displays list of items that can drop, their chances and ammounts.
  emergencyDisable:
    description: Op/console-only command. disables most of plugins functions

permissions:
  stonedrop.drop:
      description: Allow players to use /drop command.
      default: true
  stonedrop.drop.advanced:
      description: advanced /drop command.
      default: op
  stonedrop.whatdrops:
    description: Allow players to use /whatdrops command.
    default: true
  stonedrop.reload:
    description: Allow players to reload the plugin.
    default: op
  stonedrop.admin:
    description: Allow players to use /drop admin command.
    default: op
  stonedrop.chest.to-inventory:
    description: This permission applies when drop-chest-to-inventory-global is set to false. More info here https://bit.ly/3fe3eN9
    default: op
  stonedrop-exec-commands:
    description: This permission allows players to execute drop commands that require permission.
    default: op
  stonedrop.toggle-cobble:
    description: Toggle drop of cobblestone.
    default: op